# Generated by Django 6.0.4 on 2026-04-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicines/'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicine',
            name='side_effects',
            field=models.TextField(blank=True, default='Information not available'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='working_mechanism',
            field=models.TextField(blank=True, default='Information not available'),
        ),
    ]
