# Generated by Django 6.0.4 on 2026-05-31 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_email_alter_user_email_verification_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regimens', to='api.medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regimens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('regimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='api.regimen')),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_remaining', models.PositiveIntegerField(default=0)),
                ('last_restocked_at', models.DateTimeField(blank=True, null=True)),
                ('regimen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='api.regimen')),
            ],
        ),
        migrations.CreateModel(
            name='RegimenDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('missed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('taken', 'Taken'), ('missed', 'Missed')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('regimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='api.regimen')),
            ],
            options={
                'indexes': [models.Index(fields=['scheduled_at'], name='api_regimen_schedul_c3df89_idx')],
            },
        ),
    ]
