# Generated by Django 6.0.4 on 2026-06-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_regimen_stockalert_stockitem_regimendose'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='medicine',
            name='form',
            field=models.CharField(blank=True, default='tablet', max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='strength',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
