# Generated by Django 6.0.4 on 2026-07-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_medicine_description_medicine_form_medicine_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='regimendose',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='regimendose',
            name='unit',
            field=models.CharField(default='TABLET', max_length=20),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='unit',
            field=models.CharField(default='TABLET', max_length=20),
        ),
    ]
