# Generated by Django 6.0.4 on 2026-04-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_medicine_image_medicine_is_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='step_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='water_intake',
            field=models.IntegerField(default=0),
        ),
    ]
