# Generated by Django 6.0.4 on 2026-04-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_caregiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='dosage',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='frequency',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
