# Generated by Django 6.0.4 on 2026-05-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_medicine_dosage_alter_medicine_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='caregiver',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
